services:
  # L'application Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voiturepro_app
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - db

  # Le serveur Web (Nginx) - CONFIGURÉ SUR 8082
  webserver:
    image: nginx:alpine
    container_name: voiturepro_nginx
    restart: always
    ports:
      - "8082:80"  # <--- On utilise le port 8082 pour éviter les conflits
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # La base de données PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: voiturepro_db
    restart: always
    environment:
      POSTGRES_DB: parking_auto
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: BOB123bob
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: